#! /bin/sh

### BEGIN INIT INFO
# Provides:   ftj
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description:  Website
# Description:        Fundacja TAKI JESTEM website
### END INIT INFO

set -e

# /etc/init.d/ftj: start and stop the ftj service

APP_PATH=/usr/app/ftj
APP=server.js

case "$1" in
  start)
    sudo /usr/bin/node $APP_PATH/$APP > /dev/null 2>&1 &
    echo FTJ service started
  ;;
  stop)
      sudo killall -9 node
      echo FTJ service stoped
  ;;
  restart)
      sudo killall -9 node
      echo FTK service stoped
      sleep 3
      sudo /usr/bin/node $APP_PATH/$APP > /dev/null 2>&1 &
      echo FTJ service started
  ;;
  *)
      echo "Usage: /etc/init.d/ftj {start|stop|restart}"
      exit 1
esac

exit 0
